version: '3'
services:
  database:
    restart: always
    image: mysql:5.6
    ports:
      - 4306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./redis-data:/data
      - ./bundle_install:/app/vendor/bundle
      - ./bundle:/app/.bundle
      - ./node_modules:/app/node_modules
    environment:
      MYSQL_ROOT_PASSWORD: root
  app:
    build: .
    command: >
     bash -c "
       yarn install --check-files &&
       rm -f tmp/pids/server.pid &&
       bundle install --quiet &&
       bundle exec rails db:migrate:reset &&
       bundle exec rails s -p ４000 -b '0.0.0.0'
     "
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      
    
    depends_on:
      - database
  # volumes:
  #   # bundle:
  #   #   driver: local
  #   datavolume:
  #     driver: local
